controllers/AuthController.php
<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\SignupForm;
use app\models\User;
use Yii;
use yii\web\Controller;

class AuthController extends Controller
{
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }




    public function actionSignup()
    {
        $model = new SignupForm();

        if(Yii::$app->request->isPost)
        {
            $model->load(Yii::$app->request->post());
            if($model->signup())
            {
                $email = $model->email;
                $this->signupEmail($email);
                return $this->redirect(['auth/login']);
            }
        }

        return $this->render('signup', ['model'=>$model]);
    }

    public function generateToken()
    {
        return bin2hex(random_bytes(78));
    }

    public function signupEmail($email)
    {
        $token = $this->generateToken();
        $user = User::find()->where(['email'=>$email])->one();
        $user->email_confirm_token = $token;
        $user->save();
        $this->testMailer($token, $email);
        Yii::$app->session->setFlash('alerts', "We have sent you a confirmation email on $email. Please, " .
            "confirm it and then login");

    }

    public function testMailer($token, $email) {
        $url = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]/site/confirm/$token";
        Yii::$app->mailer->compose()
            ->setFrom('test-dunice@yandex.ru')
            ->setTo($email)
            ->setSubject('confirmation')
            ->setTextBody($url)
            ->setHtmlBody("<b>$url</b>")
            ->send();
    }

    public function actionTest()
    {
        $user = User::findOne(1);

        Yii::$app->user->login($user);

        if(Yii::$app->user->isGuest){
            echo 'guest';
        }else{
            echo 'user';
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Article;
use app\models\ImageUpload;
use app\models\Category;
use app\models\CreateForm;
use app\models\LoginForm;
use app\models\SendEmailForm;
use app\models\Subscription;
use app\models\Tag;
use app\models\User;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],



                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }



    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $data = Article::getAll();
        $popular = Article::getPopular();
        $recent = Article::getRecent();
        $categories = Category::getAll();

        return $this->render('index', [
            'articles'=>$data['articles'],
            'pagination'=>$data['pagination'],
            'popular'=>$popular,
            'recent'=>$recent,
            'categories'=>$categories,
        ]);
    }

    public function actionView($id){
        $article = Article::findOne($id);
        $popular = Article::getPopular();
        $recent = Article::getRecent();
        $categories = Category::getAll();

        $article->viewedCounter();

        return $this->render('single',[
            'article'=>$article,
            'popular'=>$popular,
            'recent'=>$recent,
            'categories'=>$categories,
        ]);
    }


    public function actionCategory($id){

        $data = Category::getArticlesByCategory($id);

        $popular = Article::getPopular();
        $recent = Article::getRecent();
        $categories = Category::getAll();


        return $this->render('category', [
            'articles'=>$data['articles'],
            'pagination'=>$data['pagination'],
            'popular'=>$popular,
            'recent'=>$recent,
            'categories'=>$categories,
        ]);
    }




    public function actionNew_article()
    {
        if(Yii::$app->user->isGuest && Yii::$app->user->status)
        {
            $this->redirect('/auth/login');
        }
        else
        {
            $new = new Article();
            $tags = ArrayHelper::map(Tag::find()->all(), 'id', 'title'); //массив тегов из базы
            $categories = ArrayHelper::map(Category::find()->all(), 'id', 'title'); //массив категорий из базы


            if ($new->load(Yii::$app->request->post()) && $new->save()) {
                // если статья сохранена в базе (поля: заголовок, описание, контент и дата,
                // присвоен id новой статьи в базе, приступаем теперь к сохранению тегов и категории в базу.

                $tags = Yii::$app->request->post('tags'); // массив выбранных тегов пользователем в форме
                $new->saveTags($tags); // сохраняем в таблицу article_tag выбранные теги


                $category = Yii::$app->request->post('category'); // выбранная категория пользователем в форме
                $new->saveCategory($category); // привязываем category_id к статье

                $file = UploadedFile::getInstance($new, 'image'); //получили картинку (объект)
                if ($file)
                {
                    $imageUpload = new ImageUpload();
                    $filename = $imageUpload->uploadFile($file, null); //загрузка картинки и в $filename = "название"
                    $new->saveImage($filename); // сохраняем это название
                }

                return $this->redirect(['view', 'id' => $new->id]);
            }

            return $this->render('article/new', [
                'new' => $new,
                'tags' => $tags,
                'categories' => $categories
            ]);
        }
    }

    public function actionSearch()
    {
        $popular = Article::getPopular();
        $recent = Article::getRecent();
        $categories = Category::getAll();


        $q = Yii::$app->request->get('q');
        $q = trim($q);
        $query = Article::find()->where(['like', 'title', $q]);
        $pagination = new Pagination(['totalCount'=>$query->count(), 'pageSize' => 5]);
        $articles = $query->offset($pagination->offset)->limit($pagination->limit)->all();
        return $this->render('search', compact('articles', 'pagination', 'q', 'popular', 'recent', 'categories'));
    }

    public function actionConfirm()
    {
        $token = Yii::$app->request->get('token');
        $user = User::find()->where(['email_confirm_token' => $token])->one();
        if ($user){
            $user->status = 1;
            $user->save();
        }
        return $this->redirect('/site/index');
    }
}

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Blog',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/admin/default/index']],
            ['label' => 'Articles', 'url' => ['/admin/article/index']],
            ['label' => 'Categories', 'url' => ['/admin/category/index']],
            ['label' => 'Tag', 'url' => ['/admin/tag/index']]
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\PublicAsset;
use app\widgets\Alert;
use yii\helpers\Html;
use \yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

PublicAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="https://vk.com/js/api/share.js?93" charset="windows-1251"></script>
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<nav class="navbar main-menu navbar-default">
    <div class="container">
        <div class="menu-content">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= Url::toRoute(['site/index']) ?>"><img src="../public/images/logo.jpg" alt=""></a>

            </div>


            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav text-uppercase">
                    <li><a href="<?= Url::toRoute(['site/new_article']) ?>">Create Article</a></li>

                </ul>
                <form style="display: inline-block; box-sizing: border-box; max-width: 310px; margin: 15px 30px;"
                      method="get" action="<?= Url::toRoute('site/search') ?>">
                    <input style="width: 400px" type="text" placeholder="search" name="q">
                </form>


                <div class="i_con">
                    <ul class="nav navbar-nav text-uppercase">

                        <?php if(Yii::$app->user->isGuest):?>
                            <li><a href="<?= Url::toRoute(['auth/login'])?>">Login</a></li>
                            <li><a href="<?= Url::toRoute(['auth/signup'])?>">Register</a></li>
                        <?php else: ?>

                            <?= Html::beginForm(['/auth/logout'], 'post'); ?>
                                <?php if(Yii::$app->user->identity->isAdmin):?>
                                    <?= Html::a('Admin Panel', '/admin', ['class' => 'btn btn-link logout',
                                        'style'=>"padding-top:20px; color: #ac2925"])
                                    ?>
                                <?php endif;?>

                                <?= Html::submitButton(
                                        'Logout (' . Yii::$app->user->identity->name . ')',
                                        ['class' => 'btn btn-link logout', 'style'=>"padding-top:20px;"])
                                ?>
                            <?= Html::endForm() ?>

                        <?php endif;?>
                    </ul>
                </div>


            </div>
            <!-- /.navbar-collapse -->
        </div>
    </div>
    <!-- /.container-fluid -->
</nav>


<?= $content ?>


<footer class="footer-widget-section">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <aside class="footer-widget">
                    <div class="about-img"><img src="../public/images/logo2.png" alt=""></div>
                    <div class="about-content">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
                        eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed voluptua. At vero eos et
                        accusam et justo duo dlores et ea rebum magna text ar koto din.
                    </div>
                    <div class="address">
                        <h4 class="text-uppercase">contact Info</h4>

                        <p> Dunice</p>

                        <p> Phone: +123 456 78900</p>

                        <p>my-blog.com</p>
                    </div>
                </aside>
            </div>

            <div class="col-md-4">
                <aside class="footer-widget">
                    <h3 class="widget-title text-uppercase">Testimonials</h3>

                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!--Indicator-->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <div class="single-review">
                                    <div class="review-text">
                                        <p>Lorem ipsum dolor sit amet, conssadipscing elitr, sed diam nonumy eirmod
                                            tempvidunt ut labore et dolore magna aliquyam erat,sed diam voluptua. At
                                            vero eos et accusam justo duo dolores et ea rebum.gubergren no sea takimata
                                            magna aliquyam eratma</p>
                                    </div>
                                    <div class="author-id">
                                        <img src="../public/images/author.png" alt="">

                                        <div class="author-text">
                                            <h4>Sophia</h4>

                                            <h4>CEO, ReadyTheme</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="single-review">
                                    <div class="review-text">
                                        <p>Lorem ipsum dolor sit amet, conssadipscing elitr, sed diam nonumy eirmod
                                            tempvidunt ut labore et dolore magna aliquyam erat,sed diam voluptua. At
                                            vero eos et accusam justo duo dolores et ea rebum.gubergren no sea takimata
                                            magna aliquyam eratma</p>
                                    </div>
                                    <div class="author-id">
                                        <img src="../public/images/author.png" alt="">

                                        <div class="author-text">
                                            <h4>Sophia</h4>

                                            <h4>CEO, ReadyTheme</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="single-review">
                                    <div class="review-text">
                                        <p>Lorem ipsum dolor sit amet, conssadipscing elitr, sed diam nonumy eirmod
                                            tempvidunt ut labore et dolore magna aliquyam erat,sed diam voluptua. At
                                            vero eos et accusam justo duo dolores et ea rebum.gubergren no sea takimata
                                            magna aliquyam eratma</p>
                                    </div>
                                    <div class="author-id">
                                        <img src="../public/images/author.png" alt="">

                                        <div class="author-text">
                                            <h4>Sophia</h4>

                                            <h4>CEO, ReadyTheme</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </aside>
            </div>
            <div class="col-md-4">
                <aside class="footer-widget">
                    <h3 class="widget-title text-uppercase">Custom Category Post</h3>


                    <div class="custom-post">
                        <div>
                            <a href="#"><img src="../public/images/footer-img.png" alt=""></a>
                        </div>
                        <div>
                            <a href="#" class="text-uppercase">Home is peaceful Place</a>
                            <span class="p-date">February 15, 2016</span>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <div class="footer-copy">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center">&copy; 2018 <a href="#">Treasure PRO, </a> Built with <i
                                class="fa fa-heart"></i> by <a href="#">m010sh</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>